#ifndef __GRAPH_H__
#define __GRAPH_H__

#include "frame.h"
#include "json.h"
#include "shm.h"

#ifdef __cplusplus
extern "C" {
#endif
#include "perf_dlfilter.h"
extern struct perf_dlfilter_fns perf_dlfilter_fns;
#ifdef __cplusplus
}
#endif

#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

//
// Structure tracking per-thread frame queue zones
//
struct ThreadStream
{
    uint32_t             pid{0};
    uint32_t             tid{0};
    uint32_t             current_zone_id{0};
    uint32_t             catalog_index{0};
    std::vector<ShmZone> zones;
};

//
// Lightweight timeline events generated by per-TID call-stack replay
//
enum class TimelineEventType : uint8_t
{
    START = 0,
    END   = 1,
    FULL  = 2
};

struct TimelineEvent
{
    TimelineEventType type{TimelineEventType::START};
    uint64_t          timestamp{0};
    uint64_t          start_timestamp{0}; // For END and FULL events
    uint64_t          pidtid{0};
    std::string       sym;
    std::string       dso;
    std::string       caller;
    uint16_t          cpu{0};
};

//
// Resolver for string references across worker ranks and string zones
//
class ShmStringResolver
{
public:
    ShmStringResolver() = default;
    ~ShmStringResolver();

    ShmStringResolver(const ShmStringResolver &)            = delete;
    ShmStringResolver &operator=(const ShmStringResolver &) = delete;
    ShmStringResolver(ShmStringResolver &&) noexcept;
    ShmStringResolver &operator=(ShmStringResolver &&) noexcept;

    void        AddLocalStringZones(uint32_t rank, const std::vector<ShmZone> &local_zones);
    void        LoadFromDescriptors(const std::vector<ShmZoneDescriptor> &descs);
    const char *Resolve(uint32_t rank, const StringRef &ref) const;

private:
    struct MappedEntry
    {
        int    fd{-1};
        void  *addr{nullptr};
        size_t total_size{0};
    };
    struct PoolInfo
    {
        const char *pool{nullptr};
        uint64_t    size{0};
    };

    std::unordered_map<uint64_t, MappedEntry> mapped_zones_;
    std::unordered_map<uint64_t, PoolInfo>    pools_;
};

//
// GraphDrawer is the context of dlfilter manager, responsible for:
// - managing Master Catalog SHM ("/ptgraph_master")
// - managing global String Pool SHMs ("/ptgraph_str_zone_<id>")
// - managing per-TID Frame queue SHMs ("/ptgraph_tid_<tid>_zone_<id>")
// - lock-free / atomic publishing of frame counts so other processes can read concurrently
// - converting perf_dlfilter_sample to Frame / FrameEle
//
class GraphDrawer
{
public:
    static constexpr uint32_t SHM_MAGIC               = 0x50544752; // "PTGR"
    static constexpr size_t   DEFAULT_FRAME_CAPACITY  = 65536;      // 64K frames per thread zone (~5.5 MB)
    static constexpr size_t   DEFAULT_STRING_CAPACITY = 2097152;    // 2 MB string pool
    static constexpr size_t   DEFAULT_MAX_THREADS     = 1024;       // Max threads tracked in catalog

    explicit GraphDrawer(void       *dlfilter_ctx    = nullptr,
                         std::string shm_prefix      = "ptgraph",
                         size_t      frame_capacity  = DEFAULT_FRAME_CAPACITY,
                         size_t      string_capacity = DEFAULT_STRING_CAPACITY,
                         size_t      max_threads     = DEFAULT_MAX_THREADS);

    ~GraphDrawer();

    // Non-copyable
    GraphDrawer(const GraphDrawer &)            = delete;
    GraphDrawer &operator=(const GraphDrawer &) = delete;

    // Moveable
    GraphDrawer(GraphDrawer &&) noexcept            = default;
    GraphDrawer &operator=(GraphDrawer &&) noexcept = default;

    void  SetContext(void *ctx) { ctx_ = ctx; }
    void *GetContext() const { return ctx_; }

    void SetProcRank(int rank) { proc_rank_ = rank; }
    int  GetProcRank() const { return proc_rank_; }

    void SetProcSize(int size) { proc_size_ = size; }
    int  GetProcSize() const { return proc_size_; }

    bool IsCoordinated() const { return proc_size_ > 1; }
    bool IsMainProc() const { return proc_rank_ == 0; }

    void               SetCoordId(const std::string &id) { coord_id_ = id; }
    const std::string &GetCoordId() const { return coord_id_; }

    void SetUnlinkOnDestroy(bool enable) { unlink_on_destroy_ = enable; }
    bool GetUnlinkOnDestroy() const { return unlink_on_destroy_; }

    void SetPerTidOutput(bool val) { per_tid_output_ = val; }
    bool GetPerTidOutput() const { return per_tid_output_ || json_para_.perTidOutput; }

    void               SetOutFilename(const std::string &fname) { outfilename_ = fname; }
    const std::string &GetOutFilename() const { return outfilename_; }

    void            LoadConfig(const std::string &conf_file);
    const JsonPara &GetJsonPara() const { return json_para_; }
    JsonPara       &GetJsonPara() { return json_para_; }
    int             FilterByTimestamp(uint64_t timestamp);

    const std::string &GetShmPrefix() const { return shm_prefix_; }
    size_t             GetFrameCapacity() const { return frame_capacity_; }
    size_t             GetStringCapacity() const { return string_capacity_; }

    // Register or retrieve string {shmid, offset} in the current active string pool zone.
    StringRef AppendString(const std::string &str);

    // Append a FrameEle into the thread-specific SHM queue for frame.tid.
    void AppendFrame(FrameEle frame);

    // Helper to append a frame with string resolution for sym, caller_sym, and dso.
    void AppendFrameWithSymbols(FrameEle           frame,
                                const std::string &sym,
                                const std::string &caller_sym = "",
                                const std::string &dso        = "");

    // Convert perf_dlfilter_sample to FrameEle and append to the TID-specific SHM queue.
    void AddSample(const struct perf_dlfilter_sample *sample, void *ctx = nullptr);

    // Mark all threads and master catalog as finished
    void Finish();

    // Statistics tracking
    void     IncEarlySamples() { early_samples_count_++; }
    uint64_t GetEarlySamples() const { return early_samples_count_; }

    void     IncFilteredSamples() { filtered_samples_count_++; }
    uint64_t GetFilteredSamples() const { return filtered_samples_count_; }

    uint64_t GetInsertedFrames() const { return inserted_frames_count_; }

    // Unlink all SHM segments created by this instance from /dev/shm
    void UnlinkAll();

    // Accessors
    const ShmZone                                    &GetMasterZone() const { return master_zone_; }
    const std::vector<ShmZone>                       &GetStringZones() const { return string_zones_; }
    const std::unordered_map<uint32_t, ThreadStream> &GetThreadStreams() const { return thread_streams_; }

    // Collect local zone descriptors representing all SHM zones managed by this instance
    std::vector<ShmZoneDescriptor> GetLocalZoneDescriptors() const;

    // Coordination via shared memory (replaces MPI)
    bool                           PublishLocalZonesToCoordinator();
    std::vector<ShmZoneDescriptor> CollectAllZonesFromCoordinator(int timeout_ms = 60000);

    // Generate call graph from current SHM zones (or gathered zones)
    void GenerateGraph(const std::string &outfile = "", const std::vector<ShmZoneDescriptor> &gathered_zones = {});

    // Multi-threaded generation of Perfetto timeline traces by TID
    void GeneratePerfettoTrace(const std::string &outfile, const std::vector<ShmZoneDescriptor> &all_zones);

    // Gzip compress a file
    static bool CompressFileGzip(const std::string &src_path, const std::string &dst_path);

    // Resolve string from zone and offset
    static const char *ResolveString(const ShmZone &zone, uint64_t offset);

    // Resolve string using StringRef and available string zones
    const char *ResolveString(const StringRef &ref) const;

private:
    void CreateMasterZone();
    void CreateNewStringZone();
    void CreateThreadZone(ThreadStream &stream);
    void RegisterThreadInMaster(ThreadStream &stream);
    void UpdateMasterZoneId(const ThreadStream &stream);
    void UpdateMasterTotalFrames(const ThreadStream &stream);

    void       *ctx_{nullptr};
    std::string shm_prefix_;
    size_t      frame_capacity_;
    size_t      string_capacity_;
    size_t      max_threads_;
    uint32_t    current_string_zone_id_{0};
    int         proc_rank_{0};
    int         proc_size_{1};
    std::string coord_id_{"default"};
    bool        unlink_on_destroy_{false};
    bool        is_finished_{false};
    bool        per_tid_output_{false};
    std::string outfilename_{"out.ftf"};
    uint64_t    ts_global_begin_ns_{0};
    uint64_t    ts_global_end_ns_{0};
    uint64_t    ts_rank_begin_ns_{0};
    uint64_t    ts_rank_end_ns_{0};

    JsonPara json_para_;
    uint64_t total_samples_{0};
    uint64_t early_samples_count_{0};
    uint64_t filtered_samples_count_{0};
    uint64_t inserted_frames_count_{0};

    ShmZone                                    master_zone_;
    std::vector<ShmZone>                       string_zones_;
    std::unordered_map<uint32_t, ThreadStream> thread_streams_; // tid -> stream
    std::unordered_map<std::string, StringRef> string_cache_;
};

//
// PtGraphReader: Helper class for external processes to read frames and
// symbols grouped by TID from shared memory.
//
class PtGraphReader
{
public:
    explicit PtGraphReader(std::string shm_prefix = "ptgraph");
    ~PtGraphReader();

    // Connect to the master catalog SHM
    bool OpenMaster();

    // Get snapshot of all registered threads in the master catalog
    std::vector<ThreadCatalogEntry> GetThreadEntries();

    bool GetThreadEntry(uint32_t tid, ThreadCatalogEntry &out_entry);

    // Check if the writer has finished tracing
    bool IsFinished();

    // Ensure string zone with index `zone_id` is mapped
    bool EnsureStringZone(uint8_t zone_id);

    // Resolve StringRef to string literal
    const char *ResolveString(const StringRef &ref);

    // Map a specific thread frame zone for reading
    bool OpenThreadZone(uint32_t tid, uint32_t zone_id, ShmZone &out_zone);

    // Read all available frames for a TID across all its zones
    std::vector<FrameEle> ReadAllFramesForThread(uint32_t tid);

    // Unlink all SHM zones belonging to prefix using master catalog
    static void UnlinkAll(const std::string &shm_prefix = "ptgraph");

private:
    std::string          shm_prefix_;
    ShmZone              master_zone_;
    std::vector<ShmZone> string_zones_;
};

#endif // __GRAPH_H__
